version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - gradle build
      - echo Building the Docker image...
      - docker build -t alex-codepiplinetest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo ReTaging/Pushing the Docker images...
      - docker tag alex-codepiplinetest:latest 690264925639.dkr.ecr.us-east-1.amazonaws.com/alex-codepiplinetest:latest
      - echo Pushing the Docker image...
      - docker push 690264925639.dkr.ecr.us-east-1.amazonaws.com/alex-codepiplinetest:latest
      - echo Restarting ECS service...
      - aws ecs describe-clusters
      - aws ecs update-service --force-new-deployment --cluster code-pipeline-cluster --service code-pipeline-service